api_platform:
    title: 'Social app API'
    description: 'A Symfony API to manage a collection of pictures.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    eager_loading:
        enabled: false